# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0926f52a20eefdae5649dbeb714b193a58735bde9a8b0002ad881efdca326021edcf9fd2616764537acf54ffc497cb3dfa588300c25121d9ecc1cc260c36c4dc

test:
  secret_key_base: d39c4e9640f57f22883b5ddf99d7f3fb1550f5a8deb3c94e94e41b69be6fe266b295d3fb065240bd5b92764b80c3f168711a3d1c0a281ce839c2d7f6883e15fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
